### ISSUE TITLE
Cant see anything in gui mode

### ISSUE THREAD

**Issue by nooberman12121** [DustinRepo/ChatBot#1]
I am on windows 10
Is there anyway to change these colors?
![image](https://user-images.githubusercontent.com/89046543/162619753-253debda-930f-4a47-af36-7dd791708eb7.png)

**Comment by nooberman12121** [comment]
btw nogui is broken too

**Comment by DustinRepo** [comment]
Ah, I thought I had that fixed so the output background was darker, but I guess it un-fixed itself at some point. I will look into it, and make it readable for windows again. In the meantime if you disable color in the config it should look fine, just without any color

**Comment by nooberman12121** [comment]
ty

**Comment by DustinRepo** [comment]
I've just updated the jar released in version 2.8.0 and both of these issues should be fixed now
